# Generated by Django 3.0 on 2019-12-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loantype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loantype', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loantype_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loan_app.Loantype')),
                ('employee_name', models.CharField(max_length=100)),
                ('loanamount', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFTS', 'drafts'), ('ARCHIVE', 'archive'), ('VERIFIED', 'verified')], max_length=100)),
                ('empoyee_id', models.IntegerField()),
                ('permanent_address', models.CharField(max_length=100)),
                ('temporary_address', models.CharField(max_length=100)),
                ('DOB', models.DateTimeField()),
                ('recuitdate', models.DateTimeField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_amount', models.IntegerField()),
                ('loan_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loan_app.Loan')),
                ('payment_date', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
