# Generated by Django 3.0 on 2019-12-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
