# Generated by Django 3.0 on 2019-12-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantype',
            old_name='type',
            new_name='loantype',
        ),
    ]
