# Generated by Django 3.0 on 2019-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_auto_20191204_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='recuitdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('DRAFTS', 'drafts'), ('ARCHIVE', 'archive'), ('VERIFIED', 'verified')], default='DRAFTS', max_length=10),
        ),
    ]
