# Generated by Django 3.0 on 2019-12-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_auto_20191204_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='recuitdate',
            new_name='recruitdate',
        ),
    ]
