# Generated by Django 3.0 on 2019-12-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_auto_20191204_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='empoyeeid',
            new_name='empoyee_id',
        ),
    ]
