# Generated by Django 3.0 on 2019-12-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0005_auto_20191204_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='empoyee_id',
            new_name='employee_id',
        ),
    ]
