# Generated by Django 3.0 on 2019-12-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_auto_20191204_1110'),
        ('loan_app', '0002_auto_20191205_0435'),
    ]

    operations = [
    ]
