# Generated by Django 3.0 on 2019-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_auto_20191204_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
