# Generated by Django 3.0 on 2019-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_merge_20191205_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='image2',
        ),
        migrations.AddField(
            model_name='loan',
            name='anusuchi_six_form',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='blue_print',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='close_house_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='committee_sifaris',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='dristibandha',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='inspection_report',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='lalpurja',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='malpot_receipt_1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='malpot_receipt_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='marriage_certificate',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='mun_vdc_sifaris',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='submission_form',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='verified_map',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
