# Generated by Django 3.0 on 2019-12-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_auto_20191205_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='created_on',
            field=models.CharField(default='2076-08-19', max_length=100),
        ),
    ]
